from pprint import pprint
function_operations ={'VideoReader': 'read',
 'VideoWriter': 'write',
 'addpath': 'path',
 'audioread': 'read',
 'audiowrite': 'write',
 'calllib': 'read',
 'cd': 'path',
 'csvread': 'read',
 'csvwrite': 'write',
 'diary': 'write',
 'dir': 'path',
 'dlmwrite': 'write',
 'edit': 'read',
 'eval': 'run',
 'evalin': 'run',
 'evaluateSections': 'run',
 'exist': 'path',
 'feval': 'run',
 'fgetl': 'read',
 'fgets': 'read',
 'fileattrib': 'path',
 'fileparts': 'path',
 'fileread': 'read',
 'fopen': 'write',
 'fprintf': 'write',
 'fread': 'read',
 'fscanf': 'read',
 'fullfile': 'path',
 'fwrite': 'write',
 'genpath': 'path',
 'h5read': 'read',
 'h5write': 'write',
 'import': 'read',
 'imread': 'read',
 'imwrite': 'write',
 'isfile': 'path',
 'isfolder': 'path',
 'javaaddpath': 'read',
 'jsondecode': 'read',
 'jsonencode': 'write',
 'load': 'read',
 'load_system': 'read',
 'loadlibrary': 'read',
 'ls': 'path',
 'matlab.desktop.editor.openDocument': 'read',
 'matlab.desktop.editor.save': 'write',
 'matlabroot': 'path',
 'mlappviewer': 'run',
 'ncread': 'read',
 'ncwrite': 'write',
 'netcdf.create': 'write',
 'netcdf.open': 'read',
 'open': 'read',
 'open_system': 'read',
 'openfig': 'read',
 'path': 'path',
 'pcode': 'write',
 'pwd': 'path',
 'py.importlib.import_module': 'read',
 'readmatrix': 'read',
 'readtable': 'read',
 'realpath': 'path',
 'restoredefaultpath': 'path',
 'rmpath': 'path',
 'run': 'run',
 'save': 'write',
 'save_system': 'write',
 'saveas': 'write',
 'savefig': 'write',
 'savepath': 'path',
 'sim': 'run',
 'textscan': 'read',
 'type': 'read',
 'uigetdir': 'path',
 'uigetfile': 'path',
 'uiputfile': 'path',
 'userpath': 'path',
 'what': 'path',
 'which': 'path',
 'writematrix': 'write',
 'writetable': 'write',
 'xlsread': 'read',
 'xlswrite': 'write',
 'xmlread': 'read',
 'xmlwrite': 'write'}


dangerous_functions = {
    # OS Command Execution
    'system': 'Executes operating system commands',
    'dos': 'Executes DOS command (Windows)',
    'unix': 'Executes Unix command',
    '!<command>': 'Shorthand for system command',

    # Dynamic Code Execution
    'eval': 'Executes a string as MATLAB code',
    'evalin': 'Executes a string in a specific workspace',
    'feval': 'Executes a function by name or handle',
    'str2func': 'Converts string to function handle',
    'run': 'Executes a MATLAB script',

    # External Language Interfaces
    'loadlibrary': 'Loads a shared library',
    'calllib': 'Calls function from a loaded shared library',
    'unloadlibrary': 'Unloads a shared library',
    'javaaddpath': 'Adds a JAR file to Java class path',
    'javaclasspath': 'Gets/sets Java class path',
    'import': 'Imports Java classes into MATLAB workspace',
    'javaObject': 'Creates Java object',
    'javaMethod': 'Calls Java method',
    'javaMethodEDT': 'Calls Java method on EDT thread',
    'py.*': 'Accesses Python functions or modules',
    'pyenv': 'Configures Python environment',

    # File System Manipulation
    'fopen': 'Opens a file for reading/writing',
    'fclose': 'Closes a file',
    'fread': 'Reads binary data from file',
    'fwrite': 'Writes binary data to file',
    'fprintf': 'Writes formatted data to file',
    'fscanf': 'Reads formatted data from file',
    'mkdir': 'Creates a new directory',
    'rmdir': 'Removes a directory',
    'copyfile': 'Copies a file',
    'movefile': 'Moves or renames a file',
    'delete': 'Deletes a file or object',
    'dir': 'Lists contents of a directory',
    'ls': 'Lists contents of a directory (alias for dir)',
    'fileattrib': 'Gets or sets file attributes',

    # Path Manipulation
    'addpath': 'Adds folders to MATLAB path',
    'rmpath': 'Removes folders from MATLAB path',
    'genpath': 'Generates a path including all subfolders',
    'restoredefaultpath': 'Restores the default search path',
    'savepath': 'Saves current path to disk',
    'rehash': 'Updates internal function cache',

    # GUI File Access
    'uigetfile': 'Displays file selection dialog',
    'uiputfile': 'Displays file save dialog',
    'uigetdir': 'Displays folder selection dialog',
    'uiopen': 'Open file through GUI',

    # Compilation / Packaging
    'mex': 'Compiles source code into a MEX file',
    'mcc': 'Compiles MATLAB code into a standalone app',
    'coder.*': 'Generates C/C++ code from MATLAB'
}


for func in dangerous_functions:
    if func not in function_operations:
        function_operations[func] = 'system'

# Pretty print the final merged dict
pprint(function_operations)