function weight = calculateWeight(mass)
    % calculateWeight - Calculates weight of an object given its mass
    %
    % Syntax: weight = calculateWeight(mass)
    %
    % Inputs:
    %    mass - Mass of the object in kilograms (kg)
    %
    % Outputs:
    %    weight - Weight of the object in Newtons (N)
    %
    % Example:
    %    weight = calculateWeight(10); % Calculate weight for 10 kg mass
    %
    % Author: Generated by Claude
    % Date: September 1, 2025

    % Standard gravitational acceleration on Earth (m/s^2)
    g = 9.81;
    
    % Calculate weight using W = mg
    weight = mass * g;
    
    % Display result
    fprintf('Mass: %.2f kg\n', mass);
    fprintf('Weight: %.2f N\n', weight);
end